version: '3.8'

services:
  quizos-db:
    image: postgres:16-alpine
    container_name: quizos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: quizos
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: quizos
    volumes:
      - quizos_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizos"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - root_default

  migrate:
    build:
      context: .
      target: builder
    container_name: quizos-migrate
    env_file:
      - .env
    networks:
      - root_default
    profiles: ["tools"]

  quizos:
    build:
      context: .
      shm_size: '1gb'
    container_name: quizos
    restart: unless-stopped
    depends_on:
      quizos-db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - root_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.quizos.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.quizos.entrypoints=web,websecure
      - traefik.http.routers.quizos.tls=true
      - traefik.http.routers.quizos.tls.certresolver=mytlschallenge
      - traefik.http.services.quizos.loadbalancer.server.port=3000
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: 1.7G

networks:
  root_default:
    external: true

volumes:
  quizos_pgdata: